### ISSUE TITLE
Add support for EF's with gzip compression enabled

### ISSUE THREAD

**Issue by sfc-gh-afedorov** [Snowflake-Labs/geff#27]
https://docs.snowflake.com/en/sql-reference/sql/create-external-function.html

setting compression should allow us to return >6MB from Lambdas

**Comment by sfc-gh-pkommini** [comment]
We have this issue for pypi packages extract due to the size limit:


![image](https://user-images.githubusercontent.com/72515998/140261768-bdee4ed0-530a-4b40-85c8-9f5fb0894b94.png)

**Comment by sfc-gh-ksharma** [comment]
After the code changes its working fine for pypi packages extract:

<img width="1361" alt="Screenshot 2022-06-16 at 11 35 41 AM" src="https://user-images.githubusercontent.com/100842140/174002707-13d7ce8d-85ad-4e4d-bd59-91bd4bb85eeb.png">

**Comment by sfc-gh-afedorov** [comment]
Nice! Let's push the code and make a PR?

**Comment by sfc-gh-ksharma** [comment]
PR Link:
https://github.com/Snowflake-Labs/geff/pull/56

**Comment by sfc-gh-afedorov** [comment]
fixed in #56
